- Dockerfile
- Makefile
- README.md
- Tiltfile
- Tiltfile.dev
- docker-compose.yaml
- gulpfile.js
- package.json
- src/app.ts
- src/static/sass/app.scss
- src/views/index.njk
Jira Ticket: https://companieshouse.atlassian.net/browse/SR-57
Styles requires CDN to be running, must be run with docker dev env
Instructions to run it
1. From suppression-web, run`DOCKER_BUILDKIT=1 docker build --ssh default -t suppression-web .`
2. Make sure you have latest pull of the `feature/add_suppression` branch of docker dev env
3. enable suppression and platform modules
4. `tilt up`
> add: enablers for docker environment

- Makefile
- jest.config.js
- package-lock.json
- package.json
- src/routes/paths.ts
- src/routes/routes.ts
- test/controllers/HomeController.test.ts
This commit adds `jest` as the testing, mocking and assertion framework. It also adds a simple test to verify setup.
> chore: Add jest testing framework

- README.md
Provide more relevant instructions for running suppression-web on docker environment
> chore: improve README.md instructions

- .gitignore
- .nycrc.json
- Makefile
- package-lock.json
- package.json
- sonar-project.properties
Jira Ticket: https://companieshouse.atlassian.net/browse/SR-58
> chore: add sonarQube plugin

- gulpfile.js
N/A
bug where dist directory with views is created outside of project and stops hot reloading from being possible
---
```
```
- types other than `fix:` and `feat:` …
> fix: views hot reloading

- src/controllers/ApplicantDetailsController.ts
- src/controllers/StartPageController.ts
- src/routes/routes.ts
- src/views/applicant-details.njk
- src/views/layout.njk
- test/HtmlPatternAssertions.ts
- test/controllers/ApplicantDetailsController.test.ts
- test/controllers/StartPageController.test.ts
https://companieshouse.atlassian.net/browse/SR-24
---
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, …
> feat: Transit between start page and enter your email

- src/controllers/ApplicantDetailsController.ts
- test/controllers/ApplicantDetailsController.test.ts
forgot to add previous URL to the rendering when errors are present
---
```
``` …
> fix: back button bug with errors bug

- src/controllers/AddressToRemoveController.ts
- src/models/Address.ts
- src/models/SuppressionDataModel.ts
- src/routes/paths.ts
- src/routes/routes.ts
- src/services/__mocks__/SessionService.ts
- src/validators/schema/AddressToRemoveSchema.ts
- src/validators/schema/BasicStringSchemaItem.ts
- src/views/address-to-remove.njk
- src/views/error.njk
- test/ApplicationFactory.ts
- test/HtmlPatternAssertions.ts
- test/controllers/AddressToRemoveController.test.ts
- test/services/SessionService.test.ts
- test/validators/schema/AddressToRemoveSchema.test.ts
https://companieshouse.atlassian.net/browse/SR-26
This commit implements and tests the "Address to Remove" page. It does not include navigation.
**Page:**
**Page with Errors:**
---
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be …
> feat: Address to Remove page

- package-lock.json
- package.json
- src/app.ts
- src/services/SessionService.ts
- test/ApplicationFactory.ts
- test/services/SessionService.test.ts
None
Change replaces previously used session module with CH node session handler.
---
```
```
- types other than `fix:` and `feat:` are allowed, for example …
> refactor: switch to CH node session handler

- .github/PULL_REQUEST_TEMPLATE.md
https://companieshouse.atlassian.net/browse/SR-74?focusedCommentId=152056
This commit adds an item enforcing the test coverage target to this repository's PR template.
> chore: Add coverage target to PR template

- .env.test
- package-lock.json
- package.json
- src/app.ts
- src/middleware/AuthMiddleware.ts
- src/modules/config-handler/ConfigValidation.schema.ts
- src/services/SessionService.ts
- src/utils/UriFactory.ts
- test/ApplicationFactory.ts
- test/controllers/AddressToRemoveController.test.ts
- test/controllers/ApplicantDetailsController.test.ts
- test/controllers/DocumentDetailsController.test.ts
- test/controllers/PaymentReviewController.test.ts
- test/services/SessionService.test.ts
https://companieshouse.atlassian.net/browse/SR-82
- Injected authMiddleware from `web-securty-node` lib into main app
- Auth middleware redirects user to sign in screen and then returns them to the applicant details page
- Landing page is excluded from sign in
- Updated session structure in `SessionService` and updated tests to reflect this
- Injected session/auth middleware mock into all controller tests (next PR will contain auth tests covering all routes)
N/A
---
```
```
- …
> feat: add auth middleware

- src/middleware/AuthMiddleware.ts
https://companieshouse.atlassian.net/browse/SR-82
Updated Auth Middleware to bypass sign in for the root path `http ://some-url/suppress-my-details/` (with forward slash).
Test will be added to https://github.com/companieshouse/suppression-web/pull/35
N/A
---
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API …
> fix: add check for root url with forward slash

- test/ApplicationFactory.ts
- test/controllers/AddressToRemoveController.test.ts
- test/controllers/ApplicantDetailsController.test.ts
- test/controllers/DocumentDetailsController.test.ts
- test/controllers/PaymentReviewController.test.ts
- test/middleware/AppliedAuthMiddleware.test.ts
https://companieshouse.atlassian.net/browse/SR-82
Added tests for Auth Middleware covering:
- Redirect unauthenticated user to sign in page, for all pages after landing page
- Not redirect authenticated user to sign in page, for all pages after landing page
- Not redirect unauthenticated user to sign in page, for the landing page
N/A
---
```
```
- BREAKING …
> feat: add tests for applying auth middleware to all routes

- package-lock.json
- src/models/SuppressionDataModel.ts
- src/services/session/__mocks__/SessionService.ts
- src/validators/schema/AddressToRemoveSchema.ts
- src/views/address-to-remove.njk
- test/controllers/AddressToRemoveController.test.ts
- test/services/session/SessionService.test.ts
- test/validators/schema/AddressToRemoveSchema.test.ts
[Jira Ticket](https://companieshouse.atlassian.net/browse/SR-62)
As a Suppressions user
I need to enter a country, as part of the address I want to replace
so that I can specify an address from outside UK
---
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). …
> feat: add country field to address to remove

- src/controllers/ServiceAddressController.ts
- src/models/SuppressionDataModel.ts
- src/routes/paths.ts
- src/routes/routes.ts
- src/views/service-address.njk
- test/controllers/ServiceAddressController.test.ts
- test/middleware/AppliedAuthMiddleware.test.ts
- test/services/session/SessionService.test.ts
- test/services/suppression/SuppressionService.test.ts
https://companieshouse.atlassian.net/browse/SR-34
Created new page for service address
---
```
```
- types other than `fix:` and `feat:` are allowed, for example …
> feat: add service address page

- src/controllers/ApplicantDetailsController.ts
- src/models/SuppressionDataModel.ts
- src/models/YesNo.ts
- src/validators/schema/ApplicantDetailsSchema.ts
- src/views/applicant-details.njk
- src/views/layout.njk
- src/views/start.njk
- test/controllers/ApplicantDetailsController.test.ts
- test/validators/schema/ApplicantDetailsSchema.test.ts
[Jira Ticket](https://companieshouse.atlassian.net/browse/SR-83)
---
```
``` …
> feat: support previous names

- src/controllers/ApplicantDetailsController.ts
- src/controllers/DocumentDetailsController.ts
- src/models/SuppressionDataModel.ts
- src/services/session/__mocks__/SessionService.ts
- src/utils/validation/ValidationError.ts
- src/validators/FormWithDateValidator.ts
- src/validators/schema/ApplicantDetailsSchema.ts
- src/views/applicant-details.njk
- src/views/components/date-input.njk
- test/controllers/ApplicantDetailsController.test.ts
- test/middleware/AppliedAuthMiddleware.test.ts
- test/services/session/SessionService.test.ts
- test/validators/FormWithDateValidator.test.ts
- test/validators/schema/AddressToRemoveSchema.test.ts
- test/validators/schema/ApplicantDetailsSchema.test.ts
- tslint.json
[Jira Ticket](https://companieshouse.atlassian.net/browse/SR-84)
This commit adds a Date of Birth field to the Applicant Details page and performs validation on it.
> feat: Add Date of Birth field to Applicant Details page

- .dockerignore
- Dockerfile
- README.md
- Tiltfile.dev
[Jira Ticket]()
---
```
```
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, …
> Rewrite Dockerfile to use base image

- src/controllers/HealthcheckController.ts
- src/routes/paths.ts
- src/routes/routes.ts
- test/controllers/HealthcheckController.test.ts
[Jira Ticket](https://companieshouse.atlassian.net/browse/SR-92)
Implements and tests a very basic healthcheck endpoint (`/suppress-my-details/healthcheck`, which returns status 200 (`OK`).
> chore: Implement healthcheck endpoint

- src/app.ts
- src/controllers/AddressToRemoveController.ts
- src/controllers/ApplicantDetailsController.ts
- src/controllers/DocumentDetailsController.ts
- src/controllers/PaymentReviewController.ts
- src/controllers/ServiceAddressController.ts
- src/middleware/ErrorHandler.ts
- test/ApplicationFactory.ts
- test/controllers/AddressToRemoveController.test.ts
- test/controllers/DocumentDetailsController.test.ts
- test/controllers/PaymentReviewController.test.ts
- test/controllers/ServiceAddressController.test.ts
N/A
This PR aims to:
- centralise error handling
- check for empty sessions on rendering of pages
- add tests to make sure error is rendered on empty sessions
---
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of …
> chore: add centralised default error handler

- src/controllers/PaymentReviewController.ts
fixes bug introduced in previous commit, In the codebase we save suppressions twice
---
```
```
- types other than `fix:` and `feat:` are allowed, for example …
> fix: previous commit bug - remove double suppression save

- src/app.ts
- src/controllers/CheckSubmissionController.ts
- src/modules/nunjucks/DateFilter.ts
- src/routes/paths.ts
- src/routes/routes.ts
- src/views/check-submission.njk
- test/ApplicationFactory.ts
- test/HtmlPatternAssertions.ts
- test/TestData.ts
- test/controllers/CheckSubmissionController.test.ts
- test/controllers/PaymentReviewController.test.ts
- test/modules/nunjucks/DateFilter.test.ts
[Jira Ticket](https://companieshouse.atlassian.net/browse/SR-36)
Implements and tests the Check Submission page, representing all fields currently collected by the preceding journey.
**With Previous Name**
**Without Previous Name**
> feat: Check Submission page

- src/controllers/ContactDetailsController.ts
- src/controllers/DocumentDetailsController.ts
- src/controllers/ServiceAddressController.ts
- src/models/SuppressionDataModel.ts
- src/routes/paths.ts
- src/routes/routes.ts
- src/views/contact-details.njk
- test/TestData.ts
- test/controllers/ContactDetailsController.test.ts
- test/controllers/PaymentReviewController.test.ts
- test/services/session/SessionService.test.ts
[Jira Ticket](https://companieshouse.atlassian.net/browse/SR-85)
Depends on https://github.com/companieshouse/suppression-api/pull/23
---
```
```
- types other …
> feat: add contact details page

- src/controllers/ConfirmationController.ts
- src/modules/config-handler/ConfigValidation.schema.ts
- src/routes/routes.ts
- src/services/session/SessionService.ts
- src/services/session/__mocks__/SessionService.ts
- src/views/confirmation.njk
- test/HtmlPatternAssertions.ts
- test/TestData.ts
- test/controllers/CheckSubmissionController.test.ts
- test/controllers/ConfirmationController.test.ts
- test/services/session/SessionService.test.ts
[Jira Ticket](https://companieshouse.atlassian.net/browse/SR-40)
- companieshouse/docker-chs-development#52
- companieshouse/chs-configs#1238
Implement and test the Confirmation page, which comes at the end of the Suppression Journey. It includes the following dynamic elements:
- Application Reference
- User's email address
- Document Details (in summary table)
- Amount paid by user
- Impact disclaimer event
**Note:** The Jira Ticket points to V3 of the prototype, which includes the summary table. The summary table is not present in the screenshot in the Jira Ticket. It has nevertheless been included in the interests of progress.
> feat: Confirmation page

- src/controllers/CheckSubmissionController.ts
- src/views/check-submission.njk
- src/views/contact-details.njk
- test/controllers/CheckSubmissionController.test.ts
[Jira Ticket](https://companieshouse.atlassian.net/browse/SR-85)
---
```
``` …
> feat: add contact details to check your answers page

- src/controllers/CheckSubmissionController.ts
- src/controllers/ContactDetailsController.ts
- src/controllers/PaymentReviewController.ts
- src/views/check-submission.njk
- src/views/payment-review.njk
- test/controllers/CheckSubmissionController.test.ts
- test/controllers/ContactDetailsController.test.ts
- test/controllers/PaymentReviewController.test.ts
[Jira Ticket](https://companieshouse.atlassian.net/browse/SR-72)
Implements the following navigation steps:
- Continue button on **Contact Details** page `->` **Check Your Answers** page
- Back button on **Check Your Answers** page `->` **Contact Details** page
- Continue button on **Check Your Answers** page `->` **Payment Review** page
- Back button on **Payment Review page** `->` **Check Your Answers** page
> feat: Navigation to/from Check Your Answers page

- src/controllers/ContactDetailsController.ts
- src/controllers/ServiceAddressController.ts
- src/views/contact-details.njk
- test/controllers/ContactDetailsController.test.ts
- test/controllers/ServiceAddressController.test.ts
[Jira Ticket](https://companieshouse.atlassian.net/browse/SR-89)
Service Address <-> Contact Details 
---
```
```
- types other than `fix:` and `feat:` are …
> feat: transition between replacement and contact address screens

- package-lock.json
- package.json
- src/app.ts
- src/middleware/AuthMiddleware.ts
- src/services/payment/PaymentService.ts
- src/services/session/SessionService.ts
- test/ApplicationFactory.ts
- test/middleware/AppliedAuthMiddleware.test.ts
- test/services/payment/PaymentService.test.ts
- test/services/session/SessionService.test.ts
NO JIRA
Updated Companies House dependencies to their newly published versions in the npm registry.
N/A
---
```
```
- types other than `fix:` and `feat:` are …
> chore: update CH dependencies to published ones

- src/views/confirmation.njk
https://companieshouse.atlassian.net/browse/SR-77
Updated 'Find out about call charges' link on the confirmation page to open in a new tab
N/A
---
```
```
- types …
> feat: update call charges link on confirmation page to open in new tab

- src/views/layout.njk
[Jira Ticket](https://companieshouse.atlassian.net/browse/SR-52)
Given that I am a Suppression user
When I open a web page (screen) that is part of the Suppression digital journey
Then a “BETA” banner is shown at the top of the page, under the title
And the layout and content match attached image
---
```
```
- BREAKING CHANGE: a commit that has a footer …
> feat: add feedback survey to all pages in journey

- src/views/confirmation.njk
[feedback survey opened from the confirmation page](https://companieshouse.atlassian.net/browse/SR-53)
Link was already present. Change makes sure it opens in a new tab
---
```
```
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of …
> feat: feedback survey opened from the confirmation page

- src/controllers/AccessibilityStatementController.ts
- src/routes/paths.ts
- src/routes/routes.ts
- src/views/accessibility-statement.njk
- src/views/layout.njk
- test/ApplicationFactory.ts
- test/HtmlPatternAssertions.ts
- test/controllers/AccessibilityStatementController.test.ts
- test/controllers/StartPageController.test.ts
[Accessibility statement](https://companieshouse.atlassian.net/browse/SR-106)
Adds the Accessibility Statement page, and links to it from the service footer.
> feat: Add Accessibility Statement

- src/middleware/AuthMiddleware.ts
- test/middleware/AppliedAuthMiddleware.test.ts
[Accessibility Statement](https://companieshouse.atlassian.net/browse/SR-106)
Fixes bug where sign in is unintentionally required to access the Accessibility Page.
> fix: exempt Accessibility Statement from Sign In requirement

- src/app.ts
- src/modules/nunjucks/PageTitleFilter.ts
- src/validators/schema/AddressToRemoveSchema.ts
- src/views/address-to-remove.njk
- test/ApplicationFactory.ts
- test/HtmlPatternAssertions.ts
- test/controllers/AddressToRemoveController.test.ts
- test/controllers/ContactDetailsController.test.ts
- test/validators/schema/AddressToRemoveSchema.test.ts
[Content Changes - Address Details page](https://companieshouse.atlassian.net/browse/SR-132)
Updates content and validation messages for the Address Details page.
> feat: address details page content changes

- src/views/contact-details.njk
- test/controllers/ContactDetailsController.test.ts
[Content Changes - Contact Details page](https://companieshouse.atlassian.net/browse/SR-135)
Updates content and validation messages for the Contact Details page.
> feat: Contact Details page content changes

- src/controllers/DocumentDetailsController.ts
- src/validators/FormWithDateValidator.ts
- src/validators/schema/DocumentDetailsSchema.ts
- src/views/applicant-details.njk
- src/views/components/date-input.njk
- src/views/document-details.njk
- test/controllers/DocumentDetailsController.test.ts
- test/validators/FormWithDateValidator.test.ts
- test/validators/schema/DocumentDetailsSchema.test.ts
[Content Changes - Document Details page](https://companieshouse.atlassian.net/browse/SR-133)
Updates content and validation messages for the Document Details page.
> feat: Document Details page content changes

- src/controllers/ApplicantDetailsController.ts
- src/validators/schema/ApplicantDetailsSchema.ts
- src/views/applicant-details.njk
- src/views/components/date-input.njk
- test/controllers/ApplicantDetailsController.test.ts
- test/validators/schema/ApplicantDetailsSchema.test.ts
https://companieshouse.atlassian.net/browse/SR-131
Applicant Details page content changes.
Email address will be removed in separate ticket.
---
```
```
- types …
> feat: applicant details page content changes

- src/views/service-address.njk
- test/controllers/ServiceAddressController.test.ts
https://companieshouse.atlassian.net/browse/SR-134
Service Address page content change
---
```
```
- types other than `fix:` and `feat:` are allowed, for example …
> feat: service address page content change

- src/views/check-submission.njk
- test/controllers/CheckSubmissionController.test.ts
[Content Changes - Check Your Answers page](https://companieshouse.atlassian.net/browse/SR-136)
Updates content for the Check Your Answers page.
> feat: Check Your Answers page content changes

- src/views/confirmation.njk
- test/controllers/ConfirmationController.test.ts
[Content Changes - Confirmation page](https://companieshouse.atlassian.net/browse/SR-135)
Updates content for the Confirmation page.
> feat: Confirmation page content changes

- src/views/applicant-details.njk
- src/views/components/date-input.njk
- src/views/document-details.njk
[Content Update - Document Details page](https://companieshouse.atlassian.net/browse/SR-133)
Fixes two formatting issues:
- Capitalisation of word "register" in "Comapanies House Register" in first paragraph.
- Lack of bold format in "Date the document was added to the register" field label.
> fix: Make document date field label bold

- src/views/layout.njk
[Jira Ticket](https://companieshouse.atlassian.net/browse/SR-126)
---
```
``` …
> add footer links

- src/views/confirmation.njk
[Jira Ticket](https://companieshouse.atlassian.net/browse/SR-46)
---
```
``` …
> feat: Post-submission print-out

- src/controllers/PaymentCallbackController.ts
- src/controllers/PaymentReviewController.ts
- src/routes/routes.ts
- src/services/payment/PaymentService.ts
- test/services/payment/PaymentService.test.ts
https://companieshouse.atlassian.net/browse/SR-146
Add refresh token logic to Payment API calls
N/A
---
```
```
- types other than `fix:` and `feat:` are allowed, …
> fix: add refresh token to payment api calls
